# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\redis\connection.py
# hypothesis_version: 6.137.1

[b'\r\n', b' ', b'$', b'*', b'foo', b'proto', b'server', b'version', 6000, 6379, 65536, ',', '/', '0', '2', '3', '7.4.0', 'AUTH', 'CLIENT', 'Connection', 'Connection has data', 'Connection not ready', 'ConnectionInterface', 'F', 'FALSE', 'HELLO', 'Invalid Database', 'Invalid RESP version', 'LIB-NAME', 'LIB-VER', 'N', 'NO', 'OK', 'ON', 'PING', 'PONG', 'Retry', 'SELECT', 'SETINFO', 'SETNAME', 'TRACKING', 'Too many connections', 'UNKNOWN', 'cache', 'cache_config', 'check_health', 'client_name', 'connection_class', 'db', 'decode_responses', 'default', 'encoding', 'encoding_errors', 'host', 'keys', 'localhost', 'max_connections', 'none', 'optional', 'password', 'path', 'port', 'proto', 'protocol', 'redis', 'redis-py', 'redis://', 'rediss', 'rediss://', 'required', 'retry', 'retry_on_error', 'retry_on_timeout', 'server', 'socket_keepalive', 'socket_timeout', 'ssl_check_hostname', 'strict', 'timeout', 'unix', 'unix://', 'username', 'utf-8', 'version']