# file: C:\Users\dsuth\AppData\Roaming\Python\Python312\site-packages\redis\asyncio\connection.py
# hypothesis_version: 6.137.1

[b'\n', b'\r\n', b' ', b'$', b'*', b'proto', 6000, 6379, 65536, ',', '/', '0', '2', '3', 'AUTH', 'AbstractConnection', 'CLIENT', 'Connection has data', 'Connection not ready', 'ConnectionPool', 'F', 'FALSE', 'HELLO', 'Invalid Database', 'Invalid RESP version', 'LIB-NAME', 'LIB-VER', 'N', 'NO', 'OK', 'PING', 'PONG', 'Retry', 'SELECT', 'SETINFO', 'SETNAME', 'Too many connections', 'UNKNOWN', '_CP', '__dict__', '_buffer_cutoff', '_connect_callbacks', '_lock', '_parser', '_reader', '_socket_read_size', '_writer', 'ca_certs', 'ca_data', 'cert_reqs', 'certfile', 'check_health', 'check_hostname', 'ciphers', 'client_name', 'connection_class', 'context', 'credential_provider', 'db', 'decode_responses', 'default', 'encoder', 'encoder_class', 'encoding', 'encoding_errors', 'host', 'keyfile', 'last_active_at', 'lib_name', 'lib_version', 'localhost', 'max_connections', 'min_version', 'next_health_check', 'none', 'optional', 'password', 'path', 'port', 'proto', 'protocol', 'redis', 'redis-py', 'redis_connect_func', 'rediss', 'required', 'retry_on_error', 'retry_on_timeout', 'socket', 'socket_keepalive', 'socket_timeout', 'ssl', 'ssl_check_hostname', 'ssl_context', 'strict', 'timeout', 'unix', 'username', 'utf-8']